### ISSUE TITLE
Multiple PCs on Network

### ISSUE THREAD

**Issue by Lockxish** [Mrhuma/Google-Play-Music-Overlay#1]
Any chance it'd be possible to get this working across a dual PC csetup? If the audio is playing on one PC using YTMDP, and the overlay program is on a second PC it's not able to pick up the remote feature, even though YTMDP allows a phone on the same network to control. It just crashes instead

**Comment by Mrhuma** [comment]
Hey, sorry for the late response. I did some digging and I can most definitely implement something like this. I will add an additional setting that allows you to define an IP address for the software to use instead of localhost. So you would just end up putting in the local IP of the machine running YTMDP as long as they are on the same network. I'll try and get this implemented by the end of the week.

**Comment by Mrhuma** [comment]
Added in v5.0
